directoryvol:
    image: tianon/true
    volumes:
        - /var/lib/mysql
idmvol:
    image: tianon/true
    volumes:
        - /var/lib/mysql
directorydb:
    image: mariadb
    volumes_from:
        - directoryvol
    environment: 
        - MYSQL_ROOT_PASSWORD=YHN444rty
        - MYSQL_USER=ariane
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=ariane_directory
    expose:
        - 3306
idmdb:
    image: mariadb
    volumes_from:
        - idmvol
    environment: 
        - MYSQL_ROOT_PASSWORD=YHN444rty
        - MYSQL_USER=ariane
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=ariane_idm
    expose:
        - 3306
rabbitmq:
    image: echinopsii/rabbitmq:3.3.5
    environment:
        - RABBITMQ_ADMIN_PASSWORD=admin
        - RABBITMQ_VHOST=/ariane
        - RABBITMQ_USER=ariane
        - RABBITMQ_PASSWORD=ariane
    expose:
        - 5672
    ports:
        - 15672:15672
ariane:
    image: echinopsii/ariane.community:master
    environment:
        - ARIANE_DIRECTORY_HOST=directorydb
        - ARIANE_IDM_HOST=idmdb
        - ARIANE_PLUGINS=rabbitmq:procos
        - ARIANE_RABBITMQ_HOST=rabbitmq
        - ARIANE_RABBITMQ_VHOST=/ariane
        - ARIANE_RABBITMQ_USER=ariane
        - ARIANE_RABBITMQ_PASSWORD=ariane
    ports:
        - 6969:6969
    links:
        - directorydb
        - idmdb
        - rabbitmq
